### ISSUE TITLE
Reconnection?

### ISSUE THREAD

**Issue by grigio** [flipace/lovli.js#16]
Thanks for this project, where should the reconnection be handled at react container? or horizon client? Because currently I just get a blank page if the client lose the connection with the server

**Comment by reddhouse** [comment]
@grigio I think there is some discussion on this at the horizon repo: https://github.com/rethinkdb/horizon/issues/595

**Comment by flipace** [comment]
i leave this issue open in case something needs to be changed when reconnection is there.

**Comment by nervestaple** [comment]
@flipace we're having this issue too. reconnecting would be nice, but chiefly i'm concerned about how to keep rendering everything inside the HorizonConnector in the event of disconnect. i wish the site didn't just disappear! any way around this or quick fix i could make?

**Comment by flipace** [comment]
@nervestaple this issue is related to horizon-react and the way the connector works.

as a possible workaround you can provide a prop "loadingComponent" which would be rendered in case of connection loss. alternatively we could implement a new prop which would prevent the connector from intervening when the connection is lost...

(also see: https://github.com/flipace/horizon-react/blob/master/src/components/Connector.js)

**Comment by nervestaple** [comment]
sorry yeah just realized this should have gone in horizon-react repo. let me look into this!
