### ISSUE TITLE
Needs some garbage (and possibly opinionation) collection

### ISSUE THREAD

**Issue by pkese** [flipace/lovli.js#6]
I don't understand the reason for making this boilerplate so very opinionated.   

There are some garbage packages hanging around in `package.json` (`immutable.js` is one example) sitting there for no particular reason (other than making the boilerplate more buzzword compliant and/or making the author more credible) and are never actually used in the code.

I'm actually looking for a proper horizon/react boilerplate, but seeing packages just 'prescribed' rather than actually used, makes my bullshit radar go beep and I turn away.  
Anyways, I'd much rather use Mobx than Redux for the store.

**Comment by flipace** [comment]
You can easily kick out anything you dislike.

These packages were not included because of buzz factor but because lovli itself is based upon existing apps we built and we used these packages there.

If you don't need something kick it out. If you have other flux flavor favorites, fork and replace them or create your own base from scratch.
